db:
  image: mysql:5.5
  environment:
    - MYSQL_DATABASE=plots
    - MYSQL_USER=plots
    - MYSQL_PASSWORD=plots
    - MYSQL_RANDOM_ROOT_PASSWORD=true
#
# The following can be used in production and testing.
#
#  volumes:
#    - /srv/plots_testing/database:/var/lib/mysql # for persistence
#    - /srv/plots_testing/dump:/docker-entrypoint-initdb.d # for importing a dump
#
web:
  build: .
  command: /bin/bash -c "sleep 5 && bundle exec rails s -p 4000 -b '0.0.0.0'"
  environment:
    - RAILS_ENV=test
  volumes:
    - .:/app
  ports:
    - "4000:4000"
  links:
    - db
#  restart: unless-stopped
